-- LPL Contact Driver Analytics - Database Setup
-- Run this script with ACCOUNTADMIN role in your demo account

USE ROLE ACCOUNTADMIN;

-- Create Database and Schema
CREATE DATABASE IF NOT EXISTS LPL_CONTACT_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS LPL_CONTACT_ANALYTICS.DEMO;

USE DATABASE LPL_CONTACT_ANALYTICS;
USE SCHEMA DEMO;

-- Create warehouse for Cortex AI processing
CREATE WAREHOUSE IF NOT EXISTS LPL_CORTEX_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Grant usage to public (adjust as needed)
GRANT USAGE ON DATABASE LPL_CONTACT_ANALYTICS TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA LPL_CONTACT_ANALYTICS.DEMO TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE LPL_CORTEX_WH TO ROLE PUBLIC;
