-- Contact Driver Analytics - Database Setup
-- Run this script in a Snowsight SQL Worksheet

USE ROLE SYSADMIN;

-- Create Database and Schema
CREATE DATABASE IF NOT EXISTS CONTACT_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CONTACT_ANALYTICS.ANALYTICS;

USE DATABASE CONTACT_ANALYTICS;
USE SCHEMA ANALYTICS;

-- Create warehouse for Cortex AI processing
CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Grant usage (adjust roles as needed)
GRANT USAGE ON DATABASE CONTACT_ANALYTICS TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA CONTACT_ANALYTICS.ANALYTICS TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE PUBLIC;

-- Verify setup
SELECT 'Database created' AS status, CURRENT_DATABASE() AS database_name, CURRENT_SCHEMA() AS schema_name;
